### ISSUE TITLE
reviewdog: EOF

### ISSUE THREAD

**Issue by devbranch-vitaliy** [acrollet/action-phpcs-drupal#1]
Don't work for me :( fail everytime.
```
Run acrollet/action-phpcs-drupal@v1.0.2
  with:
    filter_mode: file
    github_token: ***
    tool_name: phpcs
...
Using config file: /usr/local/bin/CodeSniffer.conf

Config value "installed_paths" added successfully
reviewdog: EOF
```

**Comment by FatherShawn** [comment]
I have the same on my first try.  Looking elsewhere I guess

**Comment by FatherShawn** [comment]
Looks like the same issue reported on the reviewdog queue: reviewdog/reviewdog#484

**Comment by weaver-sharethis** [comment]
Has anyone solved this? Having this issue on only one of our repos.

**Comment by weaver-sharethis** [comment]
Never mind, got it. The problem (for me) was too many files. The solution was to create a custom `phpcs.xml` in the project root and point to it from the `phpcs.yml`:

```yml
name: reviewdog
on: [pull_request]
jobs:
    linter_name:
        name: runner / phpcs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: oohnoitz/action-phpcs-wordpress@v1
              with:
                  github_token: ${{ secrets.GH_BOT_TOKEN }}
                  # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
                  reporter: github-pr-check
                  # Change reporter level if you need.
                  # GitHub Status Check won't become failure with warning.
                  level: error
                  phpcs_standard: './phpcs.xml'
```

Now it works fully. 👍
